@baseUrl = https://connections-api.herokuapp.com



@token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjVmOTViYWI3NGFhMzAwMTU0ZmQ2YzYiLCJpYXQiOjE3MTc1NDExMDl9.f60jM1ygwrZjfVJUDHWrHGYlfoMR2Qa5Sa3K0C606ZY';
GET  https://connections-api.herokuapp.com/users/current
Accept: application/json
Authorization: Bearer {{token}}
### Add a New Contact
POST https://connections-api.herokuapp.com/users/signup
Content-Type: application/json

{
  "name": "Nowak",
  "email": "nowak@example.com",
  "password": "67894999687"
}


# @baseUrl = https://connections-api.herokuapp.com
# @token = YOUR_TOKEN_HERE

# ### Log in to obtain token
# POST {{baseUrl}}/auth/login
# Content-Type: application/json

# {
# "name": "John ",
#   "email": "your-email@example.com",
#   "password": "your-password"
# }

# ### Get All Contacts
# GET {{baseUrl}}/contacts
# Authorization: Bearer {{token}}
# Accept: application/json